// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using insuranceManagement.Data;

namespace insuranceManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221124175805_VehicleAdded")]
    partial class VehicleAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("insuranceManagement.Data.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<int>("age");

                    b.Property<DateTime>("dob");

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.Property<int>("phone");

                    b.Property<string>("role");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("insuranceManagement.Data.Models.Vehicle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("registrationNo");

                    b.Property<int>("userId");

                    b.Property<string>("vehicleModel");

                    b.Property<string>("vehicleNo");

                    b.Property<string>("vehicleType");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("insuranceManagement.Data.Models.Vehicle", b =>
                {
                    b.HasOne("insuranceManagement.Data.Models.User", "user")
                        .WithMany("vehicles")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
