// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using insuranceManagement.Data;

namespace insuranceManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("insuranceManagement.Data.Models.Claims", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateOfAccident");

                    b.Property<string>("driverName")
                        .IsRequired();

                    b.Property<string>("licenseNo")
                        .IsRequired();

                    b.Property<string>("status");

                    b.Property<int>("userId");

                    b.Property<int>("vehicleId");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("insuranceManagement.Data.Models.Policy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("endDate");

                    b.Property<string>("policyName")
                        .IsRequired();

                    b.Property<DateTime>("startDate");

                    b.Property<int>("vehicleId");

                    b.HasKey("id");

                    b.HasIndex("vehicleId")
                        .IsUnique();

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("insuranceManagement.Data.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .IsRequired();

                    b.Property<int>("age");

                    b.Property<DateTime>("dob");

                    b.Property<string>("email");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<string>("phone")
                        .IsRequired();

                    b.Property<string>("role");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("insuranceManagement.Data.Models.Vehicle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("registrationNo")
                        .IsRequired();

                    b.Property<int>("userId");

                    b.Property<string>("vehicleModel")
                        .IsRequired();

                    b.Property<string>("vehicleNo")
                        .IsRequired();

                    b.Property<string>("vehicleType")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("insuranceManagement.Data.Models.Claims", b =>
                {
                    b.HasOne("insuranceManagement.Data.Models.User", "user")
                        .WithMany("claims")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("insuranceManagement.Data.Models.Policy", b =>
                {
                    b.HasOne("insuranceManagement.Data.Models.Vehicle", "vehicle")
                        .WithOne("policy")
                        .HasForeignKey("insuranceManagement.Data.Models.Policy", "vehicleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("insuranceManagement.Data.Models.Vehicle", b =>
                {
                    b.HasOne("insuranceManagement.Data.Models.User", "user")
                        .WithMany("vehicles")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
